In [1]:
import numpy as np
from astropy.io import fits

* Programmatically downloads numerical python (numpy) directly into environment memory namespace
* Binds `astropy` binary file streaming decoders intp local memory namespace 
* Binds high velocity C-Compiled vector calculations to a basic callback key `np`

The math: Establishes the numerical coordinate space operator to map multi-dimensional raw image pixel distributions in further pipeline calculations
$$\mathbf{M} \in \mathbb{R}^{m \times n}$$

In [2]:
mock_light_frame = np.random.randint(100, 200, size=(10, 10))

* Generates a mock light frame 10x10, two-dimensional, populated with random integers between 100 and 200 to simulate sensor noise in a raw uncalibrated frame
* Initiates a multi-dimensionl `numpy.ndarray` memory display populated with discrete integer values

The math: Initialize a discrete integer array across a localized 10x0 coordinate grid bounding target pixels values:
$$\mathbf{L}_{\text{raw}} \in \mathbb{Z}^{10 \times 10}_{[100, 200]}$$


In [3]:
print(mock_light_frame)

[[153 198 188 155 123 137 178 125 182 105]
 [193 162 138 155 130 114 150 136 197 131]
 [143 189 121 106 140 130 111 180 192 134]
 [106 183 169 135 109 102 117 195 196 177]
 [183 169 188 123 178 195 142 162 113 143]
 [111 148 188 132 187 134 140 164 131 166]
 [149 155 198 107 188 157 189 197 142 130]
 [149 105 175 196 125 149 166 170 111 190]
 [196 119 177 181 102 191 150 183 127 148]
 [183 168 151 163 171 134 153 102 193 174]]


* Directs the console memory namespace to print a visualized grid of the mock light frame with the random integer sensor noise values

In [4]:
mock_dark_frame = np.random.randint(10, 30, size = (10, 10))

* Generates a mock dark frame 10x10, two dimensional, populated with random integers between 10 and 30 to simulate sensor noise
* Initiates a multi-dimensional `numpy.ndarray` memory display populated with discrete integer values

The math: Creates a discrete integer array across a localized 10x10 coordinate grid assigning bounded integer values
$$\mathbf{L}_{\text{raw}} \in \mathbb{Z}^{10 \times 10}_{[10, 30]}$$

In [5]:
print(mock_dark_frame)

[[12 15 10 25 26 28 23 16 15 15]
 [12 11 29 17 23 17 17 18 14 19]
 [22 23 28 20 11 21 12 16 24 23]
 [22 17 16 25 21 11 13 29 10 26]
 [24 19 22 12 15 18 29 27 23 27]
 [10 12 25 16 28 15 29 21 27 13]
 [13 25 15 19 21 15 22 11 13 25]
 [14 29 14 27 21 24 20 29 26 25]
 [25 12 29 22 19 13 28 22 14 19]
 [19 26 25 20 17 11 10 14 27 16]]


* Orders console memory namespace to print a visualized grid of the mock dark frame with the random integer sensor noise values

In [6]:
master_mock_frame = mock_light_frame - mock_dark_frame

In [7]:
print(master_mock_frame)

[[141 183 178 130  97 109 155 109 167  90]
 [181 151 109 138 107  97 133 118 183 112]
 [121 166  93  86 129 109  99 164 168 111]
 [ 84 166 153 110  88  91 104 166 186 151]
 [159 150 166 111 163 177 113 135  90 116]
 [101 136 163 116 159 119 111 143 104 153]
 [136 130 183  88 167 142 167 186 129 105]
 [135  76 161 169 104 125 146 141  85 165]
 [171 107 148 159  83 178 122 161 113 129]
 [164 142 126 143 154 123 143  88 166 158]]


For both lines:
* Creates a master mock frame by grabbing the integer grid from mock light frame and subtracting the integer grid of the mock dark frame
$$\mathbf{C} = \mathbf{L}_{\text{raw}} - \mathbf{D}_{\text{master}}$$
* Commands the console memory namespace to print the new visualized grid based on the subtraction calculations of former line with the calculated integer sensor-noise-cleared values

hey first lines of code I wrote completely independently

In [8]:
sensor_temp = -12.5
max_safe_temp = -10.0

if sensor_temp > max_safe_temp:
    print(f"THERMAL WARNING - sensor temp {sensor_temp} exceeds maximum safe temperature")
else:
    print(f"THERMAL STATUS VEFIFIED - sensor temp {sensor_temp} is safely within temperature limits")

THERMAL STATUS VEFIFIED - sensor temp -12.5 is safely within temperature limits


* Creates a safety shield against sensor temperatures exceeding safety limit to guard against excess sensor noise in master stacked frame
* Attatches a warning or verifying string based on sensor temperature (float) on each individual frame

The math: Establishes a gate $T_{\text{threshold}}$ where values above threshold maximum value exported by $T_{\text{sensor}}$ are marked as outside acceptable parameters:
$$T_{\text{sensor}} \leq T_{\text{threshold}} \quad \text{where} \quad T_{\text{threshold}} = -10.0^{\circ}\text{C}$$

hey guys thats the first markdown I wrote without a template (excluding the LaTEX equations)