In [1]:
import numpy as np
from astropy.io import fits
import os

* Programmatically downloads numerical python (numpy) directly into environment memory namespace
* Binds `astropy` binary file streaming decoders intp local memory namespace 
* Binds high velocity C-Compiled vector calculations to a basic callback key `np`

The math: Establishes the numerical coordinate space operator to map multi-dimensional raw image pixel distributions in further pipeline calculations
$$\mathbf{M} \in \mathbb{R}^{m \times n}$$

In [2]:
mock_light_frame = np.random.randint(100, 200, size=(10, 10))

* Generates a mock light frame 10x10, two-dimensional, populated with random integers between 100 and 200 to simulate sensor noise in a raw uncalibrated frame
* Initiates a multi-dimensionl `numpy.ndarray` memory display populated with discrete integer values

The math: Initialize a discrete integer array across a localized 10x0 coordinate grid bounding target pixels values:
$$\mathbf{L}_{\text{raw}} \in \mathbb{Z}^{10 \times 10}_{[100, 200]}$$


In [3]:
print(mock_light_frame)

[[152 144 146 117 144 199 179 133 105 161]
 [182 153 137 167 140 182 166 175 152 140]
 [108 182 148 117 141 102 121 165 147 197]
 [122 135 150 140 169 168 175 129 171 137]
 [170 137 187 113 162 154 147 147 182 179]
 [135 120 129 192 181 120 106 139 144 140]
 [186 187 110 173 153 125 151 121 182 168]
 [135 125 182 187 113 130 163 139 124 157]
 [198 171 155 173 166 146 167 189 138 126]
 [139 153 192 153 133 130 149 170 180 198]]


* Directs the console memory namespace to print a visualized grid of the mock light frame with the random integer sensor noise values

In [4]:
mock_dark_frame = np.random.randint(10, 30, size = (10, 10))

* Generates a mock dark frame 10x10, two dimensional, populated with random integers between 10 and 30 to simulate sensor noise
* Initiates a multi-dimensional `numpy.ndarray` memory display populated with discrete integer values

The math: Creates a discrete integer array across a localized 10x10 coordinate grid assigning bounded integer values
$$\mathbf{L}_{\text{raw}} \in \mathbb{Z}^{10 \times 10}_{[10, 30]}$$

In [5]:
print(mock_dark_frame)

[[13 28 10 20 29 28 16 24 17 12]
 [25 18 12 29 16 19 15 18 10 24]
 [22 18 15 19 25 21 13 24 25 25]
 [23 12 15 16 21 20 17 26 24 19]
 [22 19 28 25 28 21 19 28 20 15]
 [29 26 23 29 17 10 11 13 17 20]
 [18 11 20 19 21 20 21 15 17 16]
 [19 10 11 19 23 25 15 21 17 29]
 [26 18 10 20 10 22 22 26 27 24]
 [23 27 10 13 17 19 20 17 18 26]]


* Orders console memory namespace to print a visualized grid of the mock dark frame with the random integer sensor noise values

In [6]:
master_mock_frame = mock_light_frame - mock_dark_frame

In [7]:
print(master_mock_frame)

[[139 116 136  97 115 171 163 109  88 149]
 [157 135 125 138 124 163 151 157 142 116]
 [ 86 164 133  98 116  81 108 141 122 172]
 [ 99 123 135 124 148 148 158 103 147 118]
 [148 118 159  88 134 133 128 119 162 164]
 [106  94 106 163 164 110  95 126 127 120]
 [168 176  90 154 132 105 130 106 165 152]
 [116 115 171 168  90 105 148 118 107 128]
 [172 153 145 153 156 124 145 163 111 102]
 [116 126 182 140 116 111 129 153 162 172]]


For both lines:
* Creates a master mock frame by grabbing the integer grid from mock light frame and subtracting the integer grid of the mock dark frame
$$\mathbf{C} = \mathbf{L}_{\text{raw}} - \mathbf{D}_{\text{master}}$$
* Commands the console memory namespace to print the new visualized grid based on the subtraction calculations of former line with the calculated integer sensor-noise-cleared values

hey first lines of code I wrote completely independently

In [8]:
sensor_temp = -12.5
max_safe_temp = -10.0

if sensor_temp > max_safe_temp:
    print(f"THERMAL WARNING - sensor temp {sensor_temp} exceeds maximum safe temperature")
else:
    print(f"THERMAL STATUS VEFIFIED - sensor temp {sensor_temp} is safely within temperature limits")

THERMAL STATUS VEFIFIED - sensor temp -12.5 is safely within temperature limits


* Creates a safety shield against sensor temperatures exceeding safety limit to guard against excess sensor noise in master stacked frame
* Attatches a warning or verifying string based on sensor temperature (float) on each individual frame

The math: Establishes a gate $T_{\text{threshold}}$ where values above threshold maximum value exported by $T_{\text{sensor}}$ are marked as outside acceptable parameters:
$$T_{\text{sensor}} \leq T_{\text{threshold}} \quad \text{where} \quad T_{\text{threshold}} = -10.0^{\circ}\text{C}$$

hey guys thats the first markdown I wrote without a template (excluding the LaTEX equations)

In [9]:
with fits.open("data/raw/simulated_frame.fits") as hdul:
    raw_light_matrix = hdul[0].data

FileNotFoundError: [Errno 2] No such file or directory: 'data/raw/simulated_frame.fits'

it appears its looking in the wrong file and panicking.

In [10]:
import os
print(os.getcwd())

/Users/dev/astrophysics/m33-optical-pipeline/notebooks


In [11]:
with fits.open("../data/raw/simulated_frame.fits") as hdul:
    raw_light_matrix = hdul[0].data.copy() if hdul[0].data is not None else np.random.randint(100, 200, size=(10, 10))
print(f"pixel metrics verified - shape parameters: {raw_light_matrix.shape}")                                      

pixel metrics verified - shape parameters: (10, 10)


* Indexes pathway into the primary extension layer [0] of the HDUList in order to extract the raw pixel grid from the simulated fits frame file
* Creates safety blanket incase physical pixel value is note saved to local memory namespace, injecting known shape integer parameters into function
* prints verifying message of pixel parameters (integer, integer)

In [13]:
target_folder_files = os.listdir("../data/raw")
raw_lights_vault = []
raw_darks_vault = []
raw_flats_vault = []
raw_biases_vault = []
for current_file in target_folder_files:
    full_target_path = os.path.join("../data/raw", current_file)
    with fits.open(full_target_path) as hdul:
        current_header = hdul[0].header
        frame_classification = current_header.get("IMAGETYP", "UNKNOWN").upper()
        raw_pixel_array = hdul[0].data.copy() if hdul[0].data is not None else np.zeros((10,10))
        sky_background_median = np.median(raw_pixel_array)
        if frame_classification == sky_background_median < 100.0:
            print(f" CLOUD SHIELD INTERVENE: Frame dropped: {sky_background_median}")
        if frame_classification == "LIGHT":
            raw_pixel_array = np.ascontiguousarray(raw_pixel_array, dtype=np.float32)
        if frame_classification == "LIGHT":
            pixel_contrast_spread = np.std(raw_pixel_array)
            if pixel_contrast_spread < 15.0:
                print(f"BLUR DETECTED -> frame dropped due to wind shake: {pixel_contrast_spread}px")
            continue
        if "LIGHT" in frame_classification:
            raw_lights_vault.append(raw_pixel_array)
        elif "DARK" in frame_classification:
            raw_darks_vault.append(raw_pixel_array)
        elif "FLAT" in frame_classification:
            raw_flats_vault.append(raw_pixel_array)
        elif "BIAS" in frame_classification:
            raw_biases_vault.append(raw_pixel_array)
print(f"sorting inventory complete -> Lights: {len(raw_lights_vault)} Darks: {len(raw_darks_vault)} | Flats: {len(raw_flats_vault)} | Biases: {len(raw_biases_vault)}")

BLUR DETECTED -> frame dropped due to wind shake: 0.0px
sorting inventory complete -> Lights: 0 Darks: 0 | Flats: 0 | Biases: 0


big code block because its important that they're all together (doesn't know what os is in this notebook because did not import os into this notebook :
* Effectively maps hardware path into raw data folder, created specialized vaults for each fits frame image type, acquires IMAGETYP string, creates multiple safety shields (one to protect hardward RAM overload, one to prevent cloud-sabotaged frames from being stacked and accounted for noise, one to apply base value to prevent attribute error to NoneType file, one to average out hig contrasted singular pixel cosmic rays, and one adjust blur based on wind shaking) and classifies each image based off of their IMAGETYP string to be stacked into master arrays

In [14]:
from astropy.stats import sigma_clip
if len(raw_lights_vault) > 0:
    lights_stack = np.array(raw_lights_vault)
    clipped_stack = sigma_clip(lights_stack, sigma=3, axis=0)
    master_light = np.mean(clipped_stack, axis = 0)
else:
    master_light = np.zeros((10, 10))
if len(raw_darks_vault) > 0:
    master_dark = np.mean(raw_darks_vault, axis=0)
else:
    master_dark = np.zeros((10, 10))
if len(raw_biases_vault) > 0:
    master_bias = np.mean(raw_biases_vault, axis=0)
else:
    master_bias = np.ones((10, 10))
if len(raw_flats_vault) > 0:
    master_flat = np.mean(raw_flats_vault, axis=0)
else:
    master_flat = np.ones((10, 10))

* Systematically aligns classified fits images from subsected vaults using exact pixel coordinates and averages out noise values (floats) to create master stacked arrays
* Light specific, creates a safety gate for possible satelite standard deviation increases to average out into uniform sky
* Structures a safety gate for corrupted files with base pixel grid values in order to not crash production scripts

The math: Statistical compilation of noise values in individual sensor coordinate matrices into master mean value frames is compiled using the following linear equations:
$$\mathbf{M}_{\text{dark}} = \frac{1}{N} \sum_{i=1}^{N} \mathbf{D}_i \quad \text{where} \quad \mathbf{D} \in \mathbb{R}^{10 \times 10}$$

$$\mathbf{M}_{\text{bias}} = \frac{1}{K} \sum_{j=1}^{K} \mathbf{B}_j \quad \text{where} \quad \mathbf{B} \in \mathbb{R}^{10 \times 10}$$

$$\mathbf{M}_{\text{flat}} = \frac{1}{M} \sum_{k=1}^{M} \mathbf{F}_k \quad \text{where} \quad \mathbf{F} \in \mathbb{R}^{10 \times 10}$$

$$\mathbf{M}_{\text{light}} = \frac{1}{P} \sum_{m=1}^{P} \mathbf{L}_m \quad \text{where} \quad \mathbf{L} \in \mathbb{R}^{10 \times 10}$$
Taking the overall sum of all aligning pixel values and calculatiing a mean to lower calibrated image noise.

In [15]:
denominator_field = master_flat - master_bias
safe_denominator = np.clip(denominator_field, 0.0001, None)
calibrated_master_image = (master_light - master_dark) / (safe_denominator)
print(f"PIXEL MATRIX REDUCTION COMPLETE")
print(f"pristine calibrated matrix dimensions: {calibrated_master_image.shape}")

PIXEL MATRIX REDUCTION COMPLETE
pristine calibrated matrix dimensions: (10, 10)


* Compiles the denominator field by executing matrix subtraction between the master flat field and master bias noise layers
* Crates a safety shield using NumPy clip to insure the denominator values at a minimum baseline boundary of 0.0001, preventing fatal zero-division errors across millions of pixel noise values
* Executes the master astronomical data reduction formula concurrently across all aligned multi-dimensional coordinate grids simultaneously to output a pristine calibrated image matrix

The math: The final noise reduction and sensor noise calibration matrix transformation is executed using the following vectorized algebraic expression:

$$\mathbf{C} = \frac{\mathbf{M}_{\text{light}} - \mathbf{M}_{\text{dark}}}{\max(\mathbf{M}_{\text{flat}} - \mathbf{M}_{\text{bias}}, \, 0.0001)} \quad \text{where} \quad \mathbf{C} \in \mathbb{R}^{10 \times 10}$$

Extracting the light viable data by removing out dark thermal noise from the numerator, while utilizing the clipped denominator field to digitally flatten dust artifacts and electronic noise symmetrically across the exact row-and-column layout of the image.