In [2]:
import numpy as np
from astropy.io import fits

* Programmatically downloads numerical python (numpy) directly into environment memory namespace
* Binds `astropy` binary file streaming decoders intp local memory namespace 
* Binds high velocity C-Compiled vector calculations to a basic callback key `np`

The math: Establishes the numerical coordinate space operator to map multi-dimensional raw image pixel distributions in further pipeline calculations
$$\mathbf{M} \in \mathbb{R}^{m \times n}$$

In [4]:
mock_light_frame = np.random.randint(100, 200, size=(10, 10))

* Generates a mock light frame 10x10, two-dimensional, populated with random integers between 100 and 200 to simulate sensor noise in a raw uncalibrated frame
* Initiates a multi-dimensionl `numpy.ndarray` memory display populated with discrete integer values

The math: Initialize a discrete integer array across a localized 10x0 coordinate grid bounding target pixels values:
$$\mathbf{L}_{\text{raw}} \in \mathbb{Z}^{10 \times 10}_{[100, 200]}$$


In [5]:
print(mock_light_frame)

[[145 157 104 112 153 193 104 106 148 139]
 [192 115 115 195 193 176 140 181 195 174]
 [136 103 196 114 166 186 160 139 183 186]
 [107 144 159 100 170 122 188 190 116 108]
 [117 180 154 132 191 169 106 102 187 144]
 [158 198 141 141 170 121 140 137 188 193]
 [192 168 130 109 114 165 152 176 166 186]
 [155 113 174 190 104 170 104 174 140 111]
 [112 138 131 162 102 138 191 187 162 123]
 [167 193 159 168 173 169 140 125 137 143]]


* Directs the console memory namespace to print a visualized grid of the mock light frame with the random integer sensor noise values

In [7]:
mock_dark_frame = np.random.randint(10, 30, size = (10, 10))

* Generates a mock dark frame 10x10, two dimensional, populated with random integers between 10 and 30 to simulate sensor noise
* Initiates a multi-dimensional `numpy.ndarray` memory display populated with discrete integer values

The math: Creates a discrete integer array across a localized 10x10 coordinate grid assigning bounded integer values
$$\mathbf{L}_{\text{raw}} \in \mathbb{Z}^{10 \times 10}_{[10, 30]}$$

In [8]:
print(mock_dark_frame)

[[29 12 13 17 12 18 15 21 16 28]
 [22 13 28 29 12 17 19 24 15 13]
 [27 17 10 17 12 26 22 15 29 17]
 [19 14 25 20 23 24 18 28 16 20]
 [19 22 13 29 14 20 26 21 15 22]
 [20 24 13 10 12 12 18 15 25 16]
 [28 10 22 11 14 27 21 22 11 20]
 [15 11 11 28 25 22 26 25 11 21]
 [20 14 28 22 22 10 10 18 28 26]
 [10 29 13 19 14 19 11 16 28 23]]


* Orders console memory namespace to print a visualized grid of the mock dark frame with the random integer sensor noise values

In [9]:
master_mock_frame = mock_light_frame - mock_dark_frame

In [10]:
print(master_mock_frame)

[[116 145  91  95 141 175  89  85 132 111]
 [170 102  87 166 181 159 121 157 180 161]
 [109  86 186  97 154 160 138 124 154 169]
 [ 88 130 134  80 147  98 170 162 100  88]
 [ 98 158 141 103 177 149  80  81 172 122]
 [138 174 128 131 158 109 122 122 163 177]
 [164 158 108  98 100 138 131 154 155 166]
 [140 102 163 162  79 148  78 149 129  90]
 [ 92 124 103 140  80 128 181 169 134  97]
 [157 164 146 149 159 150 129 109 109 120]]


For both lines:
* Creates a master mock frame by grabbing the integer grid from mock light frame and subtracting the integer grid of the mock dark frame
$$\mathbf{C} = \mathbf{L}_{\text{raw}} - \mathbf{D}_{\text{master}}$$
* Commands the console memory namespace to print the new visualized grid based on the subtraction calculations of former line with the calculated integer sensor-noise-cleared values

hey first lines of code I wrote completely independently

In [13]:
sensor_temp = -12.5
max_safe_temp = -10.0

if sensor_temp > max_safe_temp:
    print(f"THERMAL WARNING - sensor temp {sensor_temp} exceeds maximum safe temperature")
else:
    print(f"THERMAL STATUS VEFIFIED - sensor temp {sensor_temp} is safely within temperature limits")

THERMAL STATUS VEFIFIED - sensor temp -12.5 is safely within temperature limits


* Creates a safety shield against sensor temperatures exceeding safety limit to guard against excess sensor noise in master stacked frame
* Attatches a warning or verifying string based on sensor temperature (float) on each individual frame

The math: Establishes a gate $T_{\text{threshold}}$ where values above threshold maximum value exported by $T_{\text{sensor}}$ are marked as outside acceptable parameters:
$$T_{\text{sensor}} \leq T_{\text{threshold}} \quad \text{where} \quad T_{\text{threshold}} = -10.0^{\circ}\text{C}$$

hey guys thats the first markdown I wrote without a template (excluding the LaTEX equations)